language: php
sudo: required

php:
  - '5.6'

services:
  - mysql

before_script:
  - ./.scripts/travis-websetup.sh
  - composer install
  - php public/index.php orm:schema-tool:create
  - php public/index.php dbal:import .sql/data.sql

script: vendor/bin/behat
